Repository spatialos/CExampleProject, pull requests merged in 2019-08, with the labels that each got.

#28 Update to 14.0.1
  spatialos.json
  workers/c_client_direct/client.c
  workers/c_client_vtable/client.c
  workers/c_client_vtable/schema_types.c
Labels: jira/no-ticket, size/S

#29 Update launch configuration
  default_launch.json
Labels: jira/WRK, size/M

#30 Update to 14.0.2
  spatialos.json
Labels: jira/no-ticket, size/XS
